version: "3.9"
    
services:
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wp_desafio_apiki
      MYSQL_USER: apiki
      MYSQL_PASSWORD: apiki

  wordpress:
    depends_on:
      - db
    image: wordpress:5.9.3-php8.1-fpm
    container_name: wordpress
    volumes: 
      - wordpress:/var/www/html
    ports:
      - 8080:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: apiki
      WORDPRESS_DB_PASSWORD: apiki
      WORDPRESS_DB_NAME: wp_desafio_apiki
    links:
      - mysql

volumes:
  db_data: {}
  wordpress: {}